[google_service_account]
type = "service_account"
project_id = "gamificationapp-466815"
private_key_id = "af5f2c750f16657af40b5386caa20371955ce904"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQChEk1buN4EBbQO
tz+c/23QzhtutBVu81vZFd+UjcsEVJN+cCr1on2CFo/XLjJtWJpsviDE5BB/04Gl
NYSdBRR1w2PRrsjx4vm2CPopG8SyhfztIcsY20UN4KEZBu/CIzrFH5gpx8/htZOy
Yp9ANbYICwghnTxeV4sn5tr356QCdVy7bMrI32+AorIEwYjItI//qFZL5Ee2J72L
6PrI9nu8Yn71ZjR+yh0fk7Cua09ls7uXPH1eFjTDf58iJ3S0cvUsJP2LujUjSx1w
ffJOTH++rhVZd6pcU6Gqz1pz5nhzeIBgtbzm+476y7ZgP5Ngupi8RP7tJokMZiSW
GGnrRQ2/AgMBAAECggEADP8VDtmT0G9FYAqZL2nMypRW0k/litZICvQg3jOytd69
J+6VCMzbo6t+X7ZyizAjBbMxobFlQ2slgtcWpDTMudPSMhEQVbQiwfVnefmrnVwC
VH/ti0vl/oCpfwN4RQnirBUoifZ9Z5DnIfWjM+MhlPSO62dsf5BAwi92a5pdOXVt
/4OBqrekcolUXQwkcvOXYoDOdLR+/K20f7//LoaNlyGi4cDOUblu22bR3F6Te2A2
s+7il5akum/Zcw6axUjIDQNunpAuOTi3je25UwVqwNwR5LVB34d82GzOgmsY1TAK
yfVLZPaPUqtbmlnhusqs5bD+UJHRHaoWA5oNqfbygQKBgQDU+1LQ1EGGeVj61Ytv
G+R5iQW5a+gXtZcSFf3guDl5VLSaQenaibMHsOqCvq5TXqdwdzZMxBQ0K3s5iqdc
PQln0Yk4CSUdiTRhSgTr8Hv/lcYljHiBDvqyJbvKFP8/Wf6yLTQ3iLDwJ1KF94pN
4R6tealVqwxacmQPRBu48dd2mQKBgQDBmtk90U9UlxS1tr0xV/5zHlLIwmhzVYrN
ql9XVDyd0jjVbsGsU/0bZRdNij8fLTYFNjdyg99TCOKDqO0Hn+fwOFuxRjkSf83i
8e7MPJF60jWmLXk6HHuUgqw1ZQWpZoEqR6QePUbtYwdorWFrOhIO35A8Wn7L3gQ6
nLstfOJWFwKBgFu0t80Zh/laKNkguAAol3FJccCMWQxUcW8lLwLi8ERxF67QMNyb
rA3kvKV9a1yUhi5j9mqJh1WLX2zAah3KXlFopNgO//8+w+IcWBArpYjAuegTGxQf
Gg05OCnkbp+dpZCc7D35So6tr9flZZTxGR+DIkmz9AbB+JmmLvWslKUJAoGBAKBP
EfcH68JFX1afu8Sx8fVsdGvb3hUyDb8ChfOPwqmDup+wGBoTaY9Xg5YnFOFB1Gs4
W20tGKxuvPD73Vjk5W6ZnAML/JH+1YJHhc4DkQq8KMQy/yBJGWL9WI7V2XxNbkKO
E60eXC6QQ0A/4FyjNvSt1YbEAB3a9nF5+dtOfzN9AoGBAJ1J+SeFQfzpXi6A2spx
F63g5L6HaMBsU1LjkjhHVQiX6tWZf194u4QarpRr2EhVW2j9QgsdRenkRA1VNPHS
OT5DvXsYSRbATBC2x3KCQZAO/z2l2DiVpPU8ObGP/+T/jRSy9GhQTyzGFltqRQnU
y7r15ER6kyWpWHR14MN/upvc
-----END PRIVATE KEY-----
"""
client_email = "streamlit-bot@gamificationapp-466815.iam.gserviceaccount.com"
client_id = "107566175421367877189"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-bot%40gamificationapp-466815.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
